apiVersion: apps/v1
kind: Deployment
metadata:
  name: opni-metrics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opni-metrics-service
  template:
    metadata:
      labels:
        app: opni-metrics-service
    spec:
      containers:
      - name: opni-metrics-service
        image: tybalex/opni-metrics-service:dev
        imagePullPolicy: Always
        env:
        - name: PROMETHEUS_ENDPOINT
          value: "http://prometheus-operated.monitoring.svc:9090"
        - name: NATS_SERVER_URL
          value: nats://cluster-nats-client.opni.svc:4222
        - name: NKEY_SEED_FILENAME
          value: /etc/nkey/seed
        - name: ES_ENDPOINT
          value: http://opni-es-client.opni.svc:9200
        - name: ES_USERNAME
          value: admin
        - name: ES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: opni-es-password
