{
 "title": "Opni Metric Anomaly Detection Insights Dashboard",
 "description": "This dashboard provides cluster admins with the ability to monitor clusters with predictions from Opni AI",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(up, __tenant_id__)"
    }
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(kube_node_info{__tenant_id__=~\"^$cluster\"}, node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{__tenant_id__=~\"^$cluster$\",id=\"/\",node=~\"^$Node$\"}) / sum (machine_memory_bytes{__tenant_id__=~\"^$cluster$\",node=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU usage ($interval avg)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{__tenant_id__=~\"$cluster$\",id=\"/\",node=~\"^$Node$\"}[$interval])) / sum (machine_cpu_cores{__tenant_id__=~\"$cluster$\",node=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{__tenant_id__=~\"$cluster$\",node=~\"^$Node$\",id=\"/\"}) / sum (container_fs_limit_bytes{__tenant_id__=~\"$cluster$\",node=~\"^$Node$\",id=\"/\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{__tenant_id__=~\"^$cluster$\",id=\"/\",node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{__tenant_id__=~\"^$cluster$\",node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{__tenant_id__=~\"$cluster$\",id=\"/\",node=~\"^$Node$\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{__tenant_id__=~\"$cluster$\",node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{__tenant_id__=~\"$cluster$\",node=~\"^$Node$\",id=\"/\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{__tenant_id__=~\"$cluster$\",node=~\"^$Node$\",id=\"/\"})"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "MemoryUsage",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "y", "id": "1", "type": "avg" }
     ],
     "query": "metric_name:memory_usage && cluster_id:$cluster",
     "timeField": "timestamp"
    },
    {
     "alias": "LowerBound",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "yhat_lower", "id": "1", "type": "avg" }
     ],
     "query": "metric_name:memory_usage && cluster_id:$cluster",
     "timeField": "timestamp"
    },
    {
     "alias": "UpperBound",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "yhat_upper", "id": "1", "type": "avg" }
     ],
     "query": "metric_name:memory_usage && cluster_id:$cluster",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Memory Usage Anomalies and Alerts",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "metric_name:memory_usage && cluster_id:$cluster",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CpuUsage",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "y", "id": "1", "type": "avg" }
     ],
     "query": "metric_name:cpu_usage && cluster_id:$cluster",
     "timeField": "timestamp"
    },
    {
     "alias": "LowerBound",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "yhat_lower", "id": "1", "type": "avg" }
     ],
     "query": "metric_name:cpu_usage && cluster_id:$cluster",
     "timeField": "timestamp"
    },
    {
     "alias": "UpperBound",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "yhat_upper", "id": "1", "type": "avg" }
     ],
     "query": "metric_name:cpu_usage && cluster_id:$cluster",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "CPU Usage Anomalies and Alerts",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "metric_name:cpu_usage && cluster_id:$cluster",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "DiskUsage",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "y", "id": "1", "type": "avg" }
     ],
     "query": "metric_name:disk_usage && cluster_id:$cluster",
     "timeField": "timestamp"
    },
    {
     "alias": "UpperBound",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "yhat_upper", "id": "1", "type": "avg" }
     ],
     "query": "metric_name:disk_usage && cluster_id:$cluster",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Disk Usage Anomalies and Alerts",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "metric_name:disk_usage && cluster_id:$cluster",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}